// -----------------------------------------------------------------------------
// Offline support
// -----------------------------------------------------------------------------
// Why a service worker and not just file:// —
//
// file:// is a secure context per spec, so getUserMedia is not the blocker.
// The blocker is module loading. The engine fetches its SLAM chunk with a
// dynamic import (chunk-loader.ts: `await import(url)`), and it spawns workers.
// Both are cross-origin operations from a file:// page, whose origin is null,
// so both are refused. That code is inside the distributed binary, so there is
// nothing to patch.
//
// A service worker keeps the https origin — everything keeps working — while
// serving every byte from the cache. Install once with a network, run forever
// without one.

import {createHash} from 'crypto'
import {readdirSync, readFileSync, statSync, writeFileSync} from 'fs'
import {join, relative, resolve} from 'path'

const walk = (dir, base = dir) => {
  const out = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      out.push(...walk(full, base))
    } else {
      out.push(relative(base, full).split('\\').join('/'))
    }
  }
  return out
}

// Files that exist in dist but nobody requests at runtime. Precaching them
// costs install time and quota for nothing.
const SKIP = [
  /\.gitkeep$/,
  /_(original|cropped|thumbnail)\.[a-z]+$/,
  /\.map$/,
]

export const offlinePlugin = () => ({
  name: 'offline',
  closeBundle() {
    const dist = resolve(import.meta.dirname, 'dist')
    const files = walk(dist)
      .filter(f => !SKIP.some(re => re.test(f)))
      .filter(f => f !== 'sw.js')
      .sort()

    // The precache list is derived from what was actually built, so it cannot
    // drift out of sync with the output the way a hand-written list does.
    const bytes = files.reduce((n, f) => n + statSync(join(dist, f)).size, 0)

    // Version the cache by the content of everything in it. Any change to any
    // file produces a new cache name, which is what triggers the update path.
    const version = createHash('sha256')
      .update(files.map(f => `${f}:${readFileSync(join(dist, f)).length}`).join('\n'))
      .digest('hex')
      .slice(0, 12)

    const sw = `// Generated by vite.config.js — do not edit.
const CACHE = 'webar-${version}'
const PRECACHE = ${JSON.stringify(['./', ...files], null, 2)}

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE)
    // addAll is atomic: one 404 and nothing is cached. Fetch individually so a
    // single missing file degrades instead of leaving the app uninstallable.
    await Promise.all(PRECACHE.map(async (url) => {
      try {
        const res = await fetch(url, {cache: 'reload'})
        if (res.ok) {
          await cache.put(url, res)
        } else {
          console.warn('[sw] skipped', url, res.status)
        }
      } catch (e) {
        console.warn('[sw] failed', url, e.message)
      }
    }))
    // Take over on first load rather than making the user close every tab.
    await self.skipWaiting()
  })())
})

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('webar-') && key !== CACHE) {
        await caches.delete(key)
      }
    }
    await self.clients.claim()
  })())
})

self.addEventListener('fetch', event => {
  const {request} = event
  if (request.method !== 'GET') {
    return
  }

  // Cache-first. The engine is ~8 MB of immutable blobs and the app is tiny;
  // revalidating on every load would defeat the point. Updates arrive through
  // a new cache name on the next install.
  event.respondWith((async () => {
    const cached = await caches.match(request, {ignoreSearch: true})
    if (cached) {
      return cached
    }
    try {
      return await fetch(request)
    } catch (e) {
      // Offline and not precached. Navigations fall back to the shell so a
      // deep link doesn't show the browser's offline page.
      if (request.mode === 'navigate') {
        const shell = await caches.match('./')
        if (shell) {
          return shell
        }
      }
      throw e
    }
  })())
})
`
    writeFileSync(join(dist, 'sw.js'), sw)
    // eslint-disable-next-line no-console
    console.log(
      `  offline: ${files.length} files, ${(bytes / 1024 / 1024).toFixed(1)} MB precached ` +
      `(cache webar-${version})`)
  },
})
